#!/usr/bin/env node
'use strict';
/**
 * vercel-ai-sdk-best-practices - Enterprise Skill Script
 * Auto-generated by enterprise-bundle-scaffolder
 */

const fs = require('fs');
const path = require('path');

// Parse arguments
const args = process.argv.slice(2);
const options = {};
for (let i = 0; i < args.length; i++) {
  if (args[i].startsWith('--')) {
    const key = args[i].slice(2);
    const value = args[i + 1] && !args[i + 1].startsWith('--') ? args[++i] : true;
    options[key] = value;
  }
}

if (options.help) {
  console.log(`
vercel-ai-sdk-best-practices - Enterprise Skill

Usage:
  node main.cjs --check <file>    Check a file against guidelines
  node main.cjs --list            List all guidelines
  node main.cjs --help            Show this help

Description:
  Best practices for using the Vercel AI SDK in Next.js 15 applications with React Server Components and streaming capabilities.
`);
  process.exit(0);
}

if (options.list) {
  console.log('Guidelines for vercel-ai-sdk-best-practices:');
  console.log('See SKILL.md for full guidelines');
  process.exit(0);
}

console.log('vercel-ai-sdk-best-practices skill loaded. Use with Claude for code review.');
