/**
 * Clustering.js
 *
 * Implements K-Means clustering to group similar workflow execution patterns.
 * Optimized for features generated by FeatureEngineer.cjs.
 */

'use strict';

class KMeans {
    constructor(k = 5, maxIterations = 100) {
        this.k = k;
        this.maxIterations = maxIterations;
        this.centroids = [];
    }

    /**
     * Train the K-Means model on a dataset of feature vectors.
     * @param {Array<Object>} data - Array of normalized feature objects
     */
    fit(data) {
        if (data.length < this.k) {
            throw new Error(`Insufficient data for clustering. Need at least ${this.k} samples.`);
        }

        // 1. Initialize Centroids (Random Pick)
        this.centroids = this._initializeCentroids(data);

        let iterations = 0;
        let oldCentroids = [];

        // 2. Iterate until convergence
        do {
            oldCentroids = JSON.parse(JSON.stringify(this.centroids));
            const clusters = this._assignClusters(data);
            this._updateCentroids(clusters);
            iterations++;
        } while (!this._hasConverged(oldCentroids, this.centroids) && iterations < this.maxIterations);

        return {
            iterations,
            centroids: this.centroids
        };
    }

    /**
     * Predict the cluster for a single feature vector
     * @param {Object} features
     * @returns {{clusterId: number, distance: number}} Cluster ID (0 to K-1) and distance-to-centroid
     */
    predict(features) {
        let bestCluster = -1;
        let minDistance = Infinity;

        this.centroids.forEach((centroid, index) => {
            const dist = this._euclideanDistance(features, centroid);
            if (dist < minDistance) {
                minDistance = dist;
                bestCluster = index;
            }
        });

        return { clusterId: bestCluster, distance: minDistance };
    }

    _assignClusters(data) {
        const clusters = Array.from({ length: this.k }, () => []);
        data.forEach(point => {
            const prediction = this.predict(point);
            if (typeof prediction.clusterId === 'number' && clusters[prediction.clusterId]) {
                clusters[prediction.clusterId].push(point);
            }
        });
        return clusters;
    }

    _updateCentroids(clusters) {
        this.centroids = clusters.map(cluster => {
            if (cluster.length === 0) return this._randomPoint(); // Reset empty clusters

            const mean = {};
            const keys = Object.keys(cluster[0]); // Feature keys (agentSequence, totalDuration, etc)

            keys.forEach(key => {
                if (Array.isArray(cluster[0][key])) {
                    // For sequence arrays, we just avg length for simplicity in v1
                    // True sequence averaging requires DTW or embedding averaging
                    mean[key] = cluster.reduce((sum, p) => sum + p[key].length, 0) / cluster.length;
                } else {
                    mean[key] = cluster.reduce((sum, p) => sum + p[key], 0) / cluster.length;
                }
            });
            return mean;
        });
    }

    _hasConverged(oldC, newC) {
        return JSON.stringify(oldC) === JSON.stringify(newC);
    }

    _initializeCentroids(data) {
        // MaxMin Initialization (Simple K-Means++ approximation)
        // 1. Pick first centroid randomly
        const centroids = [data[Math.floor(Math.random() * data.length)]];

        // 2. Pick remaining K-1 centroids
        while (centroids.length < this.k) {
            let maxDist = -1;
            let farthestPoint = null;

            for (const point of data) {
                // Find distance to nearest existing centroid
                let minDistToCentroid = Infinity;
                for (const c of centroids) {
                    const d = this._euclideanDistance(point, c);
                    if (d < minDistToCentroid) minDistToCentroid = d;
                }

                // Keep the point that is farthest from its nearest centroid
                if (minDistToCentroid > maxDist) {
                    maxDist = minDistToCentroid;
                    farthestPoint = point;
                }
            }

            centroids.push(farthestPoint);
        }

        return centroids;
    }

    _euclideanDistance(a, b) {
        let sum = 0;
        Object.keys(a).forEach(key => {
            // Skip array features (sequences) in distance calc for V1
            if (Array.isArray(a[key]) || Array.isArray(b[key])) return;

            const valA = a[key] || 0;
            const valB = b[key] || 0;
            sum += Math.pow(valA - valB, 2);
        });
        return Math.sqrt(sum);
    }

    _randomPoint() {
        return {};
    }

    /**
     * Export model state
     */
    serialize() {
        return {
            k: this.k,
            centroids: this.centroids,
            maxIterations: this.maxIterations
        };
    }

    /**
     * Import model state
     */
    static deserialize(data) {
        const kmeans = new KMeans(data.k, data.maxIterations);
        kmeans.centroids = data.centroids;
        return kmeans;
    }
}

module.exports = KMeans;
