/**
 * QA Agent (SPEC-029)
 * ===================
 *
 * Specialized agent for verification and testing.
 * Optimized for:
 * - Analyzing code changes
 * - Planning test scenarios (Success/Fail/Edge)
 * - Generating and executing tests
 */

'use strict';

const { BaseAgent } = require('../base-agent.cjs');

class QAAgent extends BaseAgent {
  constructor(config = {}) {
    super(config);
    this.name = 'QAAgent';
  }

  /**
   * Verify a set of changes.
   *
   * Required Tools:
   * - writeFile({ file, content }): Promise<{ success }>
   * - exec({ command }): Promise<{ exitCode, stdout, stderr }>
   *
   * @param {string} taskDescription - What was done
   * @param {Array<string>} changedFiles - List of modified files
   * @returns {Promise<Object>} - Verification report
   */
  async resolveTask(taskDescription, changedFiles = []) {
    // Step 1: Plan Tests
    const testPlan = await this._planTests(taskDescription, changedFiles);

    // Validate Plan
    if (!testPlan || !Array.isArray(testPlan.tests)) {
      return {
        status: 'failure',
        error: 'Invalid test plan generated by LLM',
        testPlan,
      };
    }

    if (testPlan.tests.length === 0) {
      return {
        status: 'skipped',
        message: 'No tests generated for this task.',
        testPlan,
        results: { allPassed: true, logs: [] },
      };
    }

    // Step 2: Write Tests
    const testFiles = [];
    for (const test of testPlan.tests) {
      if (!test.filename || !test.content) continue; // Skip malformed tests

      // Use writeFile tool
      await this._useTool('writeFile', {
        file: test.filename,
        content: test.content,
      });
      testFiles.push(test.filename);
    }

    // Step 3: Run Tests
    const results = await this._runTests(testFiles);

    return {
      status: results.allPassed ? 'success' : 'failure',
      testPlan,
      results,
    };
  }

  /**
   * Generates a test plan.
   */
  async _planTests(task, files) {
    const systemPrompt = `You are an expert QA Automation Engineer.
Your goal is to write a self-contained test file (using 'node:test' and 'assert') to verify a recent change.

Context:
Task: ${task}
Changed Files: ${JSON.stringify(files)}

Output a JSON object with:
- explanation: string
- tests: Array<{ filename: string, content: string }>
  (Content must be valid JavaScript code for a node test)
`;

    const response = await this._think(systemPrompt, task);

    try {
      return JSON.parse(response);
    } catch (e) {
      throw new Error(`Failed to parse test plan: ${e.message}`);
    }
  }

  /**
   * Executes tests.
   */
  async _runTests(testFiles) {
    // In a real env, we'd run 'node --test ...'
    // Here we wrap 'exec'
    const results = { allPassed: true, logs: [] };

    for (const file of testFiles) {
      try {
        const output = await this._useTool('exec', { command: `node --test ${file}` });
        results.logs.push({
          file,
          passed: output.exitCode === 0,
          output: output.stdout || output.stderr,
        });
        if (output.exitCode !== 0) results.allPassed = false;
      } catch (e) {
        results.allPassed = false;
        results.logs.push({ file, passed: false, output: e.message });
      }
    }

    return results;
  }
}

module.exports = { QAAgent };
