/**
 * Model Client (SPEC-033)
 * =======================
 *
 * Handles interactions with LLMs.
 * Currently supports a Mock mode and a basic Anthropic API integration.
 */

'use strict';

/* global fetch */

class ModelClient {
    constructor(config = {}) {
        this.config = config;
        this.apiKey = process.env.ANTHROPIC_API_KEY || config.apiKey;
        this.modelName = config.modelName || 'claude-3-5-sonnet-20240620';
    }

    /**
     * Generate text from the LLM.
     *
     * @param {Object} params
     * @param {string} params.system - System prompt
     * @param {Array<{role: string, content: string}> | string} params.messages - User message or conversation history
     * @returns {Promise<string>} - The model's response
     */
    async generateText({ system, messages }) {
        // 1. Normalize messages
        let normalizedMessages = messages;
        if (typeof messages === 'string') {
            normalizedMessages = [{ role: 'user', content: messages }];
        }

        // 2. Check for Mock Mode
        if (!this.apiKey) {
            console.warn('[ModelClient] No API key found. Using MOCK response.');
            return this._mockResponse(system, normalizedMessages);
        }

        // 3. Call Real API (Anthropic example)
        try {
            // In a real implementation, use 'anthropic-sdk' or 'fetch'
            // For this Phase 9 pilot, we will simulate the fetch call to avoid adding heavyweight dependencies
            // unless the user explicitly requested external network calls.
            // But since the goal is "Real Intelligence", let's assume we WANT to call it if the key exists.

            // However, I cannot install new packages easily. I'll use native fetch.
            // NOTE: Node 18+ has native fetch.
            const response = await fetch('https://api.anthropic.com/v1/messages', {
                method: 'POST',
                headers: {
                    'x-api-key': this.apiKey,
                    'anthropic-version': '2023-06-01',
                    'content-type': 'application/json'
                },
                body: JSON.stringify({
                    model: this.modelName,
                    system: system,
                    messages: normalizedMessages,
                    max_tokens: 4096
                })
            });

            if (!response.ok) {
                const errText = await response.text();
                throw new Error(`Anthropic API Error: ${response.status} - ${errText}`);
            }

            const data = await response.json();
            return data.content[0].text;

        } catch (error) {
            console.error('[ModelClient] API Call Failed:', error.message);
            throw error;
        }
    }

    _mockResponse(system, messages) {
        const lastUserMessage = messages[messages.length - 1].content.toLowerCase();

        // Simple mock logic for testing
        if (lastUserMessage.includes('plan')) {
            return JSON.stringify({
                summary: 'Mock Plan',
                tasks: [{ title: 'Mock Task', description: 'Generated by MockClient' }]
            });
        }
        if (lastUserMessage.includes('test') || lastUserMessage.includes('verify')) {
            return JSON.stringify({
                tests: [{ filename: 'tests/mock.test.js', content: '// mock test' }]
            });
        }
        if (lastUserMessage.includes('fix') || lastUserMessage.includes('code')) {
            return JSON.stringify({
                actions: [{ type: 'edit', file: 'mock.js', content: '// mock code' }]
            });
        }

        return 'Mock response from ModelClient (No API Key)';
    }
}

module.exports = { ModelClient };
