#!/usr/bin/env node
'use strict';

/**
 * regulatory-compliance/scripts/main.cjs
 * CLI entry point for the regulatory-compliance skill.
 *
 * Usage:
 *   node .claude/skills/regulatory-compliance/scripts/main.cjs \
 *     --subject "User Authentication API" \
 *     --jurisdictions EU,California \
 *     --regulations GDPR,CCPA,WCAG \
 *     --scope full
 */

const path = require('path');
const fs = require('fs');

const args = process.argv.slice(2);

function getArg(name) {
  const idx = args.indexOf(`--${name}`);
  if (idx === -1) return null;
  return args[idx + 1] || null;
}

function showHelp() {
  console.log(`
regulatory-compliance — Validate systems against GDPR/CCPA, WCAG/ADA, DPA, and privacy-by-design standards.

Usage:
  node main.cjs --subject <text> [options]

Options:
  --subject           Required. The system or artifact being assessed.
  --jurisdictions     Comma-separated list: EU,California,Virginia,Colorado,Connecticut,Texas,Oregon,Montana,Florida,Global
  --regulations       Comma-separated list: GDPR,CCPA,CPRA,VCDPA,ADA,WCAG,DPA,Section508
  --scope             Assessment scope: full|gdpr-ccpa-only|accessibility-only|dpa-only|privacy-by-design-only (default: full)
  --output            Output directory for compliance report (default: .claude/context/reports/compliance/)
  --help              Show this help message

Examples:
  node main.cjs --subject "User API" --jurisdictions EU,California --regulations GDPR,CCPA
  node main.cjs --subject "Login Page" --scope accessibility-only --regulations WCAG,ADA
  node main.cjs --subject "Vendor DPA" --scope dpa-only
`);
}

if (args.includes('--help') || args.length === 0) {
  showHelp();
  process.exit(0);
}

const subject = getArg('subject');
if (!subject) {
  console.error('ERROR: --subject is required');
  showHelp();
  process.exit(1);
}

const jurisdictions = getArg('jurisdictions')
  ? getArg('jurisdictions')
      .split(',')
      .map(j => j.trim())
  : ['EU', 'California'];

const regulations = getArg('regulations')
  ? getArg('regulations')
      .split(',')
      .map(r => r.trim())
  : null;

const scope = getArg('scope') || 'full';

const validScopes = [
  'full',
  'gdpr-ccpa-only',
  'accessibility-only',
  'dpa-only',
  'privacy-by-design-only',
];
if (!validScopes.includes(scope)) {
  console.error(`ERROR: Invalid scope "${scope}". Valid: ${validScopes.join(', ')}`);
  process.exit(1);
}

const outputDir = getArg('output') || '.claude/context/reports/compliance';

// Ensure output directory exists
if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

const today = new Date().toISOString().split('T')[0];
const outputFile = path.join(
  outputDir,
  `${subject.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-compliance-${today}.md`
);

console.log(`
regulatory-compliance assessment
================================
Subject:       ${subject}
Jurisdictions: ${jurisdictions.join(', ')}
Regulations:   ${regulations ? regulations.join(', ') : 'All applicable'}
Scope:         ${scope}
Output:        ${outputFile}
Date:          ${today}

This skill is cognitive/prompt-driven. Invoke via agent context:
  Skill({ skill: 'regulatory-compliance' })

The skill will:
  1. Assess ${subject} against applicable regulations
  2. Generate structured PASS/CONDITIONAL/FAIL decision
  3. Write compliance report to: ${outputFile}

Reference: .claude/skills/regulatory-compliance/SKILL.md
`);

// Write a starter template to the output path
const reportContent = `<!-- Agent: compliance-checker | Task: # | Session: ${today} -->

# Compliance Assessment Report: ${subject}

**Assessment Date**: ${today}
**Subject**: ${subject}
**Jurisdictions**: ${jurisdictions.join(', ')}
**Regulations Assessed**: ${regulations ? regulations.join(', ') : 'GDPR, CCPA, WCAG 2.1 AA, DPA'}
**Scope**: ${scope}

> This report template was generated by regulatory-compliance/scripts/main.cjs.
> Complete the assessment by invoking Skill({ skill: 'regulatory-compliance' }) via agent context.

## Scope Definition

[Agent to complete: define assessment scope per SKILL.md Step 1]

## GDPR/CCPA Compliance Checklist

[Agent to complete: run checklist per SKILL.md Step 2]

## Privacy-by-Design Review

[Agent to complete: assess 7 principles per SKILL.md Step 3]

## ADA/WCAG Accessibility Audit

[Agent to complete: audit per SKILL.md Step 4]

## DPA Validation

[Agent to complete: validate per SKILL.md Step 5]

## Compliance Decision

\`\`\`json
{
  "decision": "PENDING",
  "regulationsAssessed": [],
  "assessmentDate": "${today}",
  "findings": [],
  "recommendedNextStep": "Complete assessment via compliance-checker agent"
}
\`\`\`
`;

fs.writeFileSync(outputFile, reportContent, 'utf8');
console.log(`Starter report template written to: ${outputFile}`);
